//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id_Games { get; set; }
        public Nullable<int> Id_Grenre { get; set; }
        public Nullable<int> Id_System_requirements { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> User_rating { get; set; }
        public Nullable<int> Critics_rating { get; set; }
        public string image { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Grenre Grenre { get; set; }
        public virtual System_requiremenst System_requiremenst { get; set; }
    }
}
